server:
  port: 8081
  servlet:
    session:
      tracking-modes: cookie
spring:
  profiles:
    active: dev
  main:
    allow-circular-references: true
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB

commons:
  cluster-node: -1