spring:
  jackson:
    default-property-inclusion: non_null # 默认忽略null值（使用@EnableWebMvc会失效）
  datasource:
    url: jdbc:mysql://suzumiya-mysql:3306/db_Rinko-Community?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    database: 0
    host: suzumiya-redis
    port: 6379
    password: 123456
  rabbitmq:
    host: suzumiya-rabbitmq
    port: 5672
    username: root
    password: 123456
    virtual-host: /
    listener:
      simple:
        prefetch: 1
        retry:
          enabled: true
          max-attempts: 3
    publisher-returns: true
  elasticsearch:
    uris: http://suzumiya-es:9200
    username: elastic
    password: 123456
  mail:
    host: smtp.163.com
    port: 25
    username: Txz2018911711@163.com
    password: HEHYFEDCCTZKFCJH
    properties:
      smtp.ssl.enable: true # 启用SSL
      smtp.socketFactory.class: SSL_FACTORY # 使用JSSE的SSL
      smtp.socketFactory.fallback: false # 只处理SSL的连接
logging:
  level:
    suzumiya.aspect.ControllerAspect: debug
    suzumiya.controller.WSChatController: debug
    suzumiya.service.impl.UserServiceImpl: debug
    suzumiya.service.impl.PostController: debug
    suzumiya.service.impl.MessageController: debug
    suzumiya.service.impl.MessageServiceImpl: debug
    suzumiya.service.impl.PostServiceImpl: debug
    suzumiya.mq.MQConsumer: debug
    suzumiya.job: debug
#  pattern:
#    dateformat: HH:mm:ss:SSS
mybatis-plus:
  #  mapper-locations: suzumiya/mapper
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  type-aliases-package: suzumiya.model.pojo

ftp:
  host: suzumiya-ftp
  port: 21
  username: ftp
  password: 123456
  encoding: UTF-8

url:
  prefix-activation-url: http://175.178.244.172/api-Rinko-Community/user/activation/
  user-login-url: http://175.178.244.172/Rinko-Community
  user-register-url: http://175.178.244.172/Rinko-Community

quartz:
  config-path: myQuartz_prod.properties